

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DrApp
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DoktorEntities : DbContext
{
    public DoktorEntities()
        : base("name=DoktorEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Doktori> Doktori { get; set; }

    public virtual DbSet<Lijekovi> Lijekovi { get; set; }

    public virtual DbSet<Pacijenti> Pacijenti { get; set; }

    public virtual DbSet<PovijestiPacijenata> PovijestiPacijenata { get; set; }

    public virtual DbSet<Pregledi> Pregledi { get; set; }

    public virtual DbSet<Recepti> Recepti { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<Uputnice> Uputnice { get; set; }

}

}

