
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DrApp
{

using System;
    using System.Collections.Generic;
    
public partial class Pacijenti
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Pacijenti()
    {

        this.Pregledi = new HashSet<Pregledi>();

        this.Recepti = new HashSet<Recepti>();

    }


    public int pacijentId { get; set; }

    public int doktorId { get; set; }

    public string ime { get; set; }

    public string prezime { get; set; }

    public string adresa { get; set; }

    public string oib { get; set; }

    public Nullable<int> povijestPacijentaId { get; set; }

    public Nullable<int> uputnicaId { get; set; }

    public string datumRodenja { get; set; }



    public virtual Doktori Doktori { get; set; }

    public virtual PovijestiPacijenata PovijestiPacijenata { get; set; }

    public virtual Uputnice Uputnice { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Pregledi> Pregledi { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Recepti> Recepti { get; set; }

}

}
