
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DrApp
{

using System;
    using System.Collections.Generic;
    
public partial class Pregledi
{

    public int pregledId { get; set; }

    public System.DateTime datum_pregleda { get; set; }

    public string napomena { get; set; }

    public Nullable<int> pacijentId { get; set; }



    public virtual Pacijenti Pacijenti { get; set; }

}

}
