
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DrApp
{

using System;
    using System.Collections.Generic;
    
public partial class Recepti
{

    public int receptId { get; set; }

    public Nullable<System.DateTime> datum { get; set; }

    public int doktorId { get; set; }

    public int pacijentId { get; set; }

    public string opis { get; set; }

    public Nullable<int> lijekId { get; set; }



    public virtual Doktori Doktori { get; set; }

    public virtual Lijekovi Lijekovi { get; set; }

    public virtual Pacijenti Pacijenti { get; set; }

}

}
